### ISSUE TITLE
クラス名が卑猥です

### ISSUE THREAD

**Issue by hotpot774** [sugawani/css-animation#1]
クラス名に`penis`とありますが、これは卑猥なので変更したほうが良いです。
例えば`piyopiyo`はどうでしょうか。

**Comment by sugawani** [comment]
@hotpot774 
`penis`は確かに不適切ですが、`piyopiyo`ではイマイチこの"VERY COOL ANIMATION"とはマッチしないような…
`peni-chan`または`parrot-stick`だとどうですかね？
[parrot参考](https://cultofthepartyparrot.com/)

**Comment by VIVIVIP** [comment]
タンタンの冒険は英語だと「The Adventures of Tintin」です。

**Comment by sugawani** [comment]
tintinで行きましょう
